//
// MongoDB schema for user data in the chatbot platform.
//
// PUBLIC_INTERFACE
// User schema (described with Mongoose-style for reference; MongoDB is schemaless, but validation is best practice)
//
// Fields:
// - _id: ObjectId (auto-generated by MongoDB)
// - username: string (unique, required)
// - email: string (unique, required)
// - password_hash: string (required)
// - created_at: Date
// - updated_at: Date
//

/** This file can be used as a reference or as a starting point for an ODM such as Mongoose in Node.js systems.
 * For purely Mongo shell usage, collections will accept these fields; optional scripts for validation may be provided in db_init.js.
 */

const userSchema = {
  bsonType: "object",
  required: ["username", "email", "password_hash"],
  properties: {
    username: {
      bsonType: "string",
      description: "Username, must be unique"
    },
    email: {
      bsonType: "string",
      description: "User email, must be unique"
    },
    password_hash: {
      bsonType: "string",
      description: "Hashed user password"
    },
    created_at: {
      bsonType: "date"
    },
    updated_at: {
      bsonType: "date"
    }
  }
};

module.exports = userSchema;
